### ISSUE TITLE
New findValue(...) helper function

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-mssql#17]
See the issue on language-postgres: https://github.com/OpenFn/language-postgresql/issues/27

**Comment by aleksa-krolls** [comment]
@lakhassane Can you clarify how the new `findValue(...)` function works to filter the query? Would it be possible to pass a complex `where` clause as a parameter? E.g...
```
SELECT Id from Parent_Table WHERE ExtCode=${data.valueX} or Code like ${data.valueY} ORDER BY CASE WHEN ExtCode=${data.valueX} then 0 else 1 END, CASE WHEN \Code=${data.valueY} then 0 else 1 END
```
Use Case: WCS may sometimes want to look-up parent records in a reference table, checking for matching records first using `ExtCode`, and then `Code` in case the first doesn't match. I'm try to evaluate whether we could use `findValue(...)` for this requirement, or if it would be better to just using raw sql to write a query like the above.

**Comment by lakhassane** [comment]
Yes it's possible with a small change @aleksa-krolls. For now I only made support for `and` but having an `or` is definitely possible.

**Comment by lakhassane** [comment]
However for the like I might need to think this through 🤔
