### ISSUE TITLE
Add options to log whole query on demand

### ISSUE THREAD

**Issue by lakhassane** [OpenFn/language-mssql#24]
Instead of logging safeQuery, some clients might request to see the whole query we are executing.

**Comment by lakhassane** [comment]
Helper function to target: 
- insertMany
- insert
- upsert
- upsertMany
- upsertIf
-

**Comment by aleksa-krolls** [comment]
@elias-ba @lakhassane Excited about this... whenever ready (not urgent), can you let me know whenever it's available on prod? And direct me to documentation on how to turn on these settings for a job? 
This will be a very helpful feature for testing loading data to a DB.

**Comment by lakhassane** [comment]
@taylordowns2000 did you have the time to look at the PR for this one?
